version: "3.7"
services:
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  gd-postgresql:
    image: postgres:15-alpine
    container_name: despesas-postgresql
    environment:
      POSTGRES_DB: gerenciamento-despesas
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5433:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - despesas-network
  # ====================================================================================================================
  # PGADMIN
  # ====================================================================================================================
  gd-pgadmin:
    image: dpage/pgadmin4
    container_name: despesas-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: me@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - 5050:80
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - gd-postgresql
    networks:
      - despesas-network

  backend:
    build: .
    container_name: despesas-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://gd-postgresql:5432/gerenciamento-despesas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234567
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      
    ports:
      - "8080:8080"
    networks:
      - despesas-network
    depends_on:
      - gd-pgadmin
    
networks:
  despesas-network:
    driver: bridge