version: "3.7"
services:
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  dt-postgresql:
    image: postgres:15-alpine
    container_name: exponse-postgresql
    environment:
      POSTGRES_DB: dimitracker
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5433:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - exponse-network
  # ====================================================================================================================
  # PGADMIN
  # ====================================================================================================================
  dt-pgadmin:
    image: dpage/pgadmin4
    container_name: exponse-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: me@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - 5050:80
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - dt-postgresql
    networks:
      - exponse-network

  backend:
    build: .
    container_name: exponse-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dt-postgresql:5432/dimetracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234567
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      
    ports:
      - "8080:8080"
    networks:
      - exponse-network
    depends_on:
      - dt-pgadmin
    
networks:
  exponse-network:
    driver: bridge